### ISSUE TITLE
Uncaught Error: Class 'CloudFlare\IpRewrite' not found

### ISSUE THREAD

**Issue by sachinghare** [NeverBehave/rc_hcaptcha#1]
Thanks for the nice plugin. 

1. Activated plugin successfully
2. Can see the hCaptcha on login page

whether the captcha is validate or not it is giving error after clicking login button

PHP Fatal error:  Uncaught Error: Class 'CloudFlare\IpRewrite' not found in /public_html/mail/plugins/rc_hcaptcha/rc_hcaptcha.php:38
Stack trace:
#0 /public_html/mail/program/lib/Roundcube/rcube_plugin_api.php(469): rc_hcaptcha->authenticate(Array)
#1 /public_html/mail/index.php(114): rcube_plugin_api->exec_hook('authenticate', Array)
#2 {main}
  thrown in /public_html/mail/plugins/rc_hcaptcha/rc_hcaptcha.php on line 38

The "vendor" directory located inside /plugins/rc_hcaptcha/
so the path of vendor directory like /plugins/rc_hcaptcha/vendor/

Can you tell us why?

Regards
Sachin G.

**Comment by sachinghare** [comment]
Ended up with no communication helped me develop our own code. Thanks for not replying 👍

**Comment by NeverBehave** [comment]
If you follow the get-started guide then installer should resolved the dependency. Vendor should be in root/project directory.

I have worked on migrating away from gmail to Fastmail and this issue does not have notification in my mailbox. I know this is a late reply so I will close this issue now, but if anyone has update plz feel free reply below. 

P.S. I am personally using this project so it is under maintenance, but I won’t possibly have time for new features as I am still a student right now. Remote learning doesn’t really go smoothly especially when you don’t have good internet access :|
